import type { Metadata } from "next";
import { Unbounded } from "next/font/google";
import "./globals.css";

const unboundedSans = Unbounded({
  variable: "--font-unbounded-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${unboundedSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
